### ISSUE TITLE
Icons colors are replaced and then be compared to new colors when switching colorschemes

### ISSUE THREAD

**Issue by Kirxii** [rachartier/tiny-devicons-auto-colors.nvim#11]
### Description

I'm using nvim-tree and neo-tree with nvim-web-devicons and tiny-devicon-auto-color in a minimal setup. After setting up only `autoreload = true` in the configurations, I decided to constantly change colorschemes to see what would happen.

What I discovered is that the original icon colors are overwritten by the colorscheme's own choice of colors, which when change into another colorscheme, the new colors are then replaced with the newer choices of colors.

Essentially: original colors > colorscheme 1's colors > colorscheme 2's colors > etc...

It would eventually reduce the amount of colors to just a few, if not, just one, which is not that great with plenty of icon colors. Or it would mess up the colors if the colorscheme is missing some certain colors, or if the algorithm just decides that an entirely different color is the closest to it.

This would be best seen if `cache` is enabled within the plugin and read the cache file to compare before and after the change.

Is this an intended feature? If so, I think it would make much more sense to store the original colors somewhere to compare to the colorschemes'?

**Comment by rachartier** [comment]
Hello!
You're right. Thanks for the feedback, it should be good now.
