### ISSUE TITLE
Wrong icon color when switching from base16-gruvbox-dark-hard to another

### ISSUE THREAD

**Issue by BBFifield** [rachartier/tiny-devicons-auto-colors.nvim#12]
I'm using the color schemes from base16-nvim and as you can see in the first screenshot, the Lua icon is usually blue when using a catppuccin variant, however when switching from base16-gruvbox-dark-hard to catppuccin, it turns green. Any reason for this?

![satty-20241204-21:00:33](https://github.com/user-attachments/assets/4fc4d7de-3ee8-48ec-b83f-aa9b5fbe81f8)
![satty-20241204-21:00:54](https://github.com/user-attachments/assets/cc49ecc0-ab0f-4697-ac6c-7d63a34922cd)
![satty-20241204-21:01:19](https://github.com/user-attachments/assets/72209c94-2449-49b4-baf4-20cb21015f0e)

**Comment by rachartier** [comment]
Hi,
Can you please try to disable the cache in `opts` and redo the switching?

**Comment by BBFifield** [comment]
Hello, I tried disabling the cache in opts but the issue persists. And if it makes any difference, I also deleted the cache file located in ~/.cache/nvim before retrying the color scheme switching.

**Comment by rachartier** [comment]
Oh, sorry, I think I misunderstood the issue. Is the issue when you switch themes directly inside Neovim (like with a theme switcher or something similar), or is it when you update the colorscheme you use in your config file?

**Comment by rachartier** [comment]
Cause I think the issue comes from the colorscheme itself: 
![image](https://github.com/user-attachments/assets/a26049bb-65cd-4454-986a-610133fc8f45)
There is no blue! (or I think, I'm colorblind)

Multiple solutions:

- You can ignore a file by doing like so:

```lua
require('tiny-devicons-auto-colors').setup({
    ignore = {
        "lua",
    }
}
```

- You can try to add a blue shade when passing the colors table.
- You can try to tweaks the `factors` table to better match the blue shade (if there is)

**Comment by BBFifield** [comment]
Sorry I explained the issue very poorly.

But yup! it's when switching color schemes directly from inside Neovim.

For instance. If I start Neovim with base16-catppuccin-frappe set as my theme, the lua icon's color correctly appears as the blue declared in the theme palette,  `#8caaee`.

![satty-20241205-19:31:48](https://github.com/user-attachments/assets/416e21ec-8750-4142-a28d-ae4aa9b31093)

Now, if you switch the theme to base16-gruvbox-dark-hard by executing `:colorscheme base16-gruvbox-dark-hard` from inside Neovim, the lua icon color will update as it should to `#83a598`, which happens to be that theme's version of blue as far as I know. Everything works as it should up to this point.

![satty-20241205-19:31:29](https://github.com/user-attachments/assets/505ddde8-0fa6-46a1-a889-ea2acce572ce)

So what happens when you switch the theme right back to base16-catppuccin-frappe? Well you end up with a lua icon color which looks nothing like the blue from the first time using base16-catppuccin-frappe and instead looks a yellowish green, `#a6d189`.

![satty-20241205-19:32:10](https://github.com/user-attachments/assets/11f504bc-e583-46ce-8d51-0847a3c38b3e)

Well that ain't right! You can also see that if you switch the theme to base16-gruvbox-dark-hard once again, the icon doesn't become the same color from the first time you switched to base16-gruvbox-dark-hard, but also a yellowish green color! `#b8bb26`

![satty-20241205-19:32:35](https://github.com/user-attachments/assets/a2dd2213-f92a-4338-b002-c3b4639db8d2)

This is all from one Neovim session btw, so no restarts between any of the theme switches during bug reproduction.

It's almost as if the plugin is comparing `#83a598` from gruvbox instead of the original lua icon color to the next theme's color palette.

**Comment by rachartier** [comment]
Thank you a lot for all these infos.

I've thrown together a patch so that you can now switch themes without this bug.
In the next few days, I'll do another pass to optimize further.

Tell me if it's all good for you !

**Comment by BBFifield** [comment]
> Thank you a lot for all these infos.
> 
> I've thrown together a patch so that you can now switch themes without this bug. In the next few days, I'll do another pass to optimize further.
> 
> Tell me if it's all good for you !

Seems like the patch fixed the original bug but may have introduced a regression.

This time, if you start Neovim with base16-gruvbox-dark-hard set as your default theme (in config file) and then switch to base16-catppuccin-frappe (by using `:colorscheme base16-catppuccin-frappe`), the lua icon color isn't `#8caaee` (as it is when the frappe is set to the default) but `#51576d` instead.

![satty-20241205-23:44:34](https://github.com/user-attachments/assets/833cdfd4-3a06-466b-9527-b2a8e1b743e6)

The same issue occurs when you set your default theme to base16-catppuccin-latte and switch to base16-gruvbox-dark-hard, as you can see in the two screenshots below.

![satty-20241205-23:50:02](https://github.com/user-attachments/assets/ff273da1-33f1-40ce-a0a7-81fc81a3c23b)
![satty-20241206-00:10:50](https://github.com/user-attachments/assets/b6a2f2e2-c205-4b62-84d1-7523bc4fadcf)

**Comment by rachartier** [comment]
I cannot reproduce this issue, did you enabled `autoreload` in your config?

**Comment by BBFifield** [comment]
> I cannot reproduce this issue, did you enabled `autoreload` in your config?

I do have autoreload enabled.

One thing that did fix it initially was disabling `event = VeryLazy`, which is what's listed as default in the installation guide for Lazy.nvim.

However, disabling this event means that when you delete both cache files and then open Neovim again, the plugin will complain about missing cache, after which a cache file will be regenerated. This cache file will contain the wrong default colors (at least for lua, haven't checked for other file types but I assume they're also wrong).
