### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lpnh** [rachartier/tiny-devicons-auto-colors.nvim#7]
Hi! First of all, I would like to say thank you for providing us with this plugin. I really love it.
In fact, I love it so much that I made a tool based on your plugin to apply the same colors to [Yazi](https://github.com/sxyazi/yazi) icons. The thing is, there's no License here, and I'm also not an expert on this topic. So I'm asking for your permission to use your code.

Here's a link to the repo: https://github.com/lpnh/icons-brew.yazi
Your code can be found here: https://github.com/lpnh/icons-brew.yazi/tree/main/prepare

If you opt for a compatible License, I think I can attach it to the same path.

**Comment by rachartier** [comment]
Hello!
Thank you very much, it's great to see my project being used elsewhere!

I've added a MIT Licence. I must confess that I'm not very well-informed about licenses either... But the MIT license normally allows all code modifications. 

I think you need to mention the project however, but it seems that you already did it, so it's all good !

**Comment by lpnh** [comment]
I've included the license: https://github.com/lpnh/icons-brew.yazi/commit/137dc4cb789f46b24405b6be39dafe99b14ab562

Thanks again, and please feel free to reach out to me anytime.
