### ISSUE TITLE
Caching broken again

### ISSUE THREAD

**Issue by simonmandlik** [rachartier/tiny-devicons-auto-colors.nvim#8]
The same problem as described here https://github.com/rachartier/tiny-devicons-auto-colors.nvim/issues/5 started appearing after latest package update.

It disappears when caching is disabled

**Comment by rachartier** [comment]
I've added another check. With it, I can't reproduce the issue.

Can you tell me if it works for you ?

```lua
    {
        "rachartier/tiny-devicons-auto-colors.nvim",
	branch = "8-caching-broken-again",
        dependencies = { "nvim-tree/nvim-web-devicons" },
        config = function()
            require('tiny-devicons-auto-colors').setup()
        end
    }
```

**Comment by simonmandlik** [comment]
Looks fixed, thanks!
